from django.core.exceptions import ValidationError

def validate_faculty_name(name):
    pass